import hihatWAV from './hihat.wav';
import openhatWAV from './openhat.wav';
import snareWAV from './snare2.wav';
import kickWAV from './kick3.wav';
import tomWAV from './tom.wav';
import rideWAV from './ride.wav';
import crash1WAV from './crash1.wav';
import crash2WAV from './crash2.wav';
import chinaWAV from './china.wav';
import cowbellWAV from './cowbell.wav';

export const hihat = new Audio(hihatWAV);
export const openhat = new Audio(openhatWAV);
export const snare = new Audio(snareWAV);
export const kick = new Audio(kickWAV);
export const tom = new Audio(tomWAV);
export const ride = new Audio(rideWAV);
export const crash1 = new Audio(crash1WAV);
export const crash2 = new Audio(crash2WAV);
export const china = new Audio(chinaWAV);
export const cowbell = new Audio(cowbellWAV);
