import hihatWAV from './hihat.wav';
import openhatWAV from './openhat.wav';
import snareWAV from './snare2.wav';
import kickWAV from './kick3.wav';
import tomWAV from './tom.wav';
import rideWAV from './ride.wav';
import crash1WAV from './crash1.wav';
import crash2WAV from './crash2.wav';
import chinaWAV from './china.wav';
import cowbellWAV from './cowbell.wav';
import handclapWAV from './handclap.wav';
import applauseWAV from './APPLAUS2.wav';
import shoryukenMP3 from './shoryuken.mp3';
import hadokenMP3 from './hadoken.mp3';

export const hihat = new Audio(hihatWAV);
export const openhat = new Audio(openhatWAV);
export const snare = new Audio(snareWAV);
export const kick = new Audio(kickWAV);
export const tom = new Audio(tomWAV);
export const ride = new Audio(rideWAV);
export const crash1 = new Audio(crash1WAV);
export const crash2 = new Audio(crash2WAV);
export const china = new Audio(chinaWAV);
export const cowbell = new Audio(cowbellWAV);
export const applause = new Audio(applauseWAV);
export const clap = new Audio(handclapWAV);
export const shoryuken = new Audio(shoryukenMP3);
export const hadoken = new Audio(hadokenMP3);
